super_config:
  workers:
    -
      scalable: true
      min_worker: 1
      max_worker: 10
      cmd: 'php bin/console'
      parameters:
        number: 2
        log_dir: '/var/log'
        name: 'Name'
    -
      scalable: true
      min_worker: 1
      max_worker: 10
      cmd: 'php bin/console'
      parameters:
        number: 2
        log_dir: '/var/log'
        name: 'Name'
